[build]
  publish = "public"

[[headers]]
  for = "/*"
  
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"

[[redirects]]
    /api/* /api/:splat 200
    /_ /index.html 200
    /\* /index.html 404

[[headers]]
  for = "/.netlify/functions/*"
  
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
